- name: topics
  connection: local
  hosts: localhost
#  environment:
#    ZOOKEEPER: 
#      - localhost:2181
  tasks:
    - name: single topic foobar
      kafka_topic:
        name: alot
        state: present
        partitions: 2
        replication_factor: 2
        bootstrap_server:
         - "[::1]:9092"
         - localhost:9092
         - 127.0.0.1:9092
        zookeeper:
         - localhost:2181
        cleanup_policy: delete
        compression_type: gzip
        delete_retention_time: 10ms
        file_delete_delay_time: 10ms
        flush_messages: 50
        flush_time: 10ms
        follower_replication_throttled_replicas: "*"
        index_interval_size: 100kB
        leader_replication_throttled_replicas: "*"
        max_compaction_lag_time: 6d
        max_message_size: 1MiB
        message_format_version: 2.1-IV0
        message_timestamp_difference_max_time: 10ms
        message_timestamp_type: LogAppendTime
        min_cleanable_dirty_ratio: 0.6
        min_compaction_lag_time: 10ms
        min_insync_replicas: 1
        preallocate: true
        retention_size: 1000B
        retention_time: -1
        segment_size: 21B
        segment_index_size: 4KiB
        segment_jitter_time: 12ms
        segment_time: 30ms
        unclean_leader_election_enable: true
        message_downconversion_enable: true
